version: '3.5'

services:
  Aurora.Identity.API:
    image: aurora/identity-api:1.0
    build:
      context: .
      dockerfile: Services/Identity/Aurora.Identity.API/Dockerfile
    container_name: Aurora.Identity.API
    networks:
      - aurora-api

  Aurora.Common.API:
    image: aurora/common-api:1.0
    build:
      context: .
      dockerfile: Services/Common/Aurora.Common.API/Dockerfile
    container_name: Aurora.Common.API
    networks:
      - aurora-api

  Aurora.Platform.API:
    image: aurora/platform-api:1.0
    build:
      context: .
      dockerfile: Services/Platform/Aurora.Platform.API/Dockerfile
    container_name: Aurora.Platform.API
    networks:
      - aurora-api

  Aurora.Platform.Gateway:
    image: aurora/platform-gateway:1.0
    build:
      context: .
      dockerfile: Gateway/Aurora.Platform.Gateway/Dockerfile
    container_name: Aurora.Platform.Gateway
    networks:
      - aurora-api

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.1
    container_name: elasticsearch
    ports:
      - 9200:9200
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    networks:
      - aurora-api
    environment:
      - xpack.monitoring.enabled=true
      - xpack.watcher.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node

  kibana:
    image: docker.elastic.co/kibana/kibana:7.6.1
    container_name: kibana
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    networks:
      - aurora-api
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200

networks:
  aurora-api:
    name: aurora-api

volumes:
  elasticsearch-data: